import "./globals.css";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";
import { AppLayout } from "@/components/ui/app-layout";
import type { Metadata } from "next";
import { ReactQueryProvider } from "./react-query-provider";

import '@solana/wallet-adapter-react-ui/styles.css'
import { SolanaProvider } from "@/components/solana/solana-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <AppLayout>{children}</AppLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
